version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: configs
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8081:80"
